image:
  - "Visual Studio 2015"

environment:
  matrix:
    - TARGET: mingw64
      PYTHON: 'python2'
    - TARGET: mingw64
      PYTHON: 'python3'
    - TARGET: win32
      PYTHON: "C:\\Python27-x64\\python"
    - TARGET: win32
      PYTHON: "C:\\Python35-x64\\python"
    - TARGET: win32
      PYTHON: "C:\\Python36-x64\\python"
    - TARGET: win32
      PYTHON: "C:\\Python37-x64\\python"

matrix:
  allow_failures:
    - TARGET: mingw64

install:
  - cmd: IF [%TARGET%]==[win32] ( choco install swig && refreshenv )

    # Setup %SHELL%
  - cmd: IF [%TARGET%]==[win32] SET "SHELL=cmd /c"
  - cmd: IF [%TARGET%]==[mingw64] SET "SHELL=C:\\msys64\\usr\\bin\\env MSYSTEM=MINGW64 MSYS2_PATH_TYPE=minimal /usr/bin/sh -e -l -c --"

    # Setup %PATH%/$PATH
  - cmd: IF [%TARGET%]==[mingw64] SET "MSYS2_PATH_TYPE=minimal"

    # Setup initial environment for msys/cygwin
  - cmd: IF [%TARGET%]==[mingw64] %SHELL% "echo 'cd %APPVEYOR_BUILD_FOLDER%' | sed -e 's/^\\(\\w\\):/\\/\\l\\1/' -e 's/\\\\/\\//g' | tee -a ~/.profile"
  - cmd: IF [%TARGET%]==[mingw64] %SHELL% "echo 'PATH=~/.local/bin:$PATH' | tee -a ~/.profile"

    # Install packages
  - cmd: IF [%TARGET%]==[mingw64] %SHELL% "pacman -S --noconfirm --needed mingw-w64-x86_64-%PYTHON% mingw-w64-x86_64-%PYTHON%-pip base-devel mingw-w64-x86_64-toolchain"
  - cmd: "%SHELL% \"%PYTHON% -m pip install --user -U pip\""
  - cmd: "%SHELL% \"%PYTHON% -m pip install --user pipenv\""
  - cmd: "%SHELL% \"%PYTHON% -m pipenv install --dev\""
  - cmd: "%SHELL% \"%PYTHON% -m pipenv run python bin/downloads.py\""

before_test:
  - cmd: "%SHELL% \"%PYTHON% -m pipenv --version\""
  - cmd: "%SHELL% \"%PYTHON% -m pipenv run python --version\""
  - cmd: "%SHELL% \"%PYTHON% -m pipenv run scons --version\""

build: off

test_script:
  - cmd: "%SHELL% \"%PYTHON% -m pipenv run python runtest --verbose=2 -e test/system\""
