image:
  - "Visual Studio 2015"

environment:
  matrix:
    - TARGET: mingw64
      PYTHON: "C:\\msys64\\mingw64\\bin"
      PYPATH: "C:\\msys64\\home\\appveyor\\.local\\bin;%PYTHON%;C:\\msys64\\usr\\local\\bin;C:\\msys64\\usr\\bin"
      PY: python2
    - TARGET: mingw64
      PYTHON: "C:\\msys64\\mingw64\\bin"
      PYPATH: "C:\\msys64\\home\\appveyor\\.local\\bin;%PYTHON%;C:\\msys64\\usr\\local\\bin;C:\\msys64\\usr\\bin"
      PY: python3
    - TARGET: win32
      PYTHON: "C:\\Python27-x64"
      PYPATH: "%APPDATA%\\Python\\Scripts;%PYTHON%;%PYTHON%\\Scripts"
      PY: python
    - TARGET: win32
      PYTHON: "C:\\Python35-x64"
      PYPATH: "%APPDATA%\\Python\\Python35\\Scripts;%PYTHON%;%PYTHON%\\Scripts"
      PY: python
    - TARGET: win32
      PYTHON: "C:\\Python36-x64"
      PYPATH: "%APPDATA%\\Python\\Python36\\Scripts;%PYTHON%;%PYTHON%\\Scripts"
      PY: python
    - TARGET: win32
      PYTHON: "C:\\Python37-x64"
      PYPATH: "%APPDATA%\\Python\\Python37\\Scripts;%PYTHON%;%PYTHON%\\Scripts"
      PY: python

matrix:
  allow_failures:
    - TARGET: mingw64
    - PYTHON: "C:\\Python27-x64"

install:
    # variables for: mingw64
  - IF [%TARGET%]==[mingw64] SET "PATH=%PYPATH%;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0"
  - IF [%TARGET%]==[mingw64] SET "SHELL=C:\\msys64\\usr\\bin\\env MSYSTEM=MINGW64 MSYS2_PATH_TYPE=minimal /usr/bin/sh -e -l -c --"
  - IF [%TARGET%]==[mingw64] SET "MSYS2_PATH_TYPE=minimal"
    # variables for: win 32
  - IF [%TARGET%]==[win32] ( choco install swig && refreshenv )
  - IF [%TARGET%]==[win32] SET "PATH=%PYPATH%;%PATH%"
    # install comands
  - .appveyor/install-%TARGET%.bat

before_test:
  - .appveyor/before_test-%TARGET%.bat

build: off

test_script:
  - .appveyor/test_script-%TARGET%.bat
