language:
  python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

# Ubuntu Xenial (Travis default as of 2020.04) has swig 3.0 which doesn't work
# with python>=3.8, so I allow failures with 3.8 and later.
matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.8"
    - python: "3.9-dev"

addons:
  apt:
    packages:
      - swig

before_install:
  - export REQUIREMENTS_DEV_TXT=`python -c 'import sys;print("requirements" + str(sys.version_info.major) + "-dev.txt")'`
  - echo "REQUIREMENTS_DEV_TXT=$REQUIREMENTS_DEV_TXT"

install:
  - pip install -U pip
  - pip --version
  - pip install -r requirements.txt
  - pip install -r "$REQUIREMENTS_DEV_TXT"
  - python bin/downloads.py


before_script:
  - which python
  - which swig
  - swig -version

script:
  - python runtest --verbose=2 -e test/system
